#!/usr/bin/env python3
"""Generate host adapters for hci-spine from a single CANONICAL source.

The skill is authored once at ~/.claude/skills/hci-spine (canonical). Codex's skill
validator rejects the `argument-hint` / `allowed-tools` frontmatter and wants an
`agents/openai.yaml`, so this emits a Codex-compatible COPY (real files, not symlinks
— symlinks break Windows checkouts and zip installs) at ~/.codex/skills/hci-spine.

Re-runnable: regenerates the adapter in place. Refuses to overwrite a directory that
was not produced by this tool (no ADAPTER_GENERATED.md) unless --force, and never
writes onto the canonical source.

Usage: build_adapters.py [--dest DIR] [--dry-run] [--force]
"""
from __future__ import annotations

import argparse
import shutil
import sys
from pathlib import Path

CANONICAL = Path(__file__).resolve().parent.parent  # the hci-spine dir
MARKER = "ADAPTER_GENERATED.md"
SKIP = {"__pycache__", ".git", ".DS_Store", MARKER}

OPENAI_YAML = '''interface:
  display_name: "HCI-Spine"
  short_description: "HCI paper full-pipeline orchestrator + project state machine"
  default_prompt: "Use $hci-spine to run an HCI paper end to end: route by contribution form, walk the gated lifecycle (forge→…→paper), and produce a submission-ready manuscript."
'''


def strip_frontmatter_keys(text: str, drop=("argument-hint:", "allowed-tools:")) -> str:
    """Remove Codex-incompatible keys from the leading --- frontmatter block only."""
    if not text.startswith("---"):
        return text
    lines = text.splitlines(keepends=True)
    end = next((i for i in range(1, len(lines)) if lines[i].strip() == "---"), None)
    if end is None:
        return text
    kept = lines[:1] + [l for l in lines[1:end] if not l.lstrip().startswith(drop)] + lines[end:]
    return "".join(kept)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--dest", default=str(Path.home() / ".codex/skills/hci-spine"))
    ap.add_argument("--dry-run", action="store_true")
    ap.add_argument("--force", action="store_true")
    a = ap.parse_args()
    dest = Path(a.dest).resolve()

    if dest == CANONICAL:
        print("ERROR: dest equals the canonical source; refusing.", file=sys.stderr)
        return 2
    if dest.exists() and not (dest / MARKER).exists() and any(dest.iterdir()) and not a.force:
        print(f"ERROR: {dest} exists and was not generated by this tool. Use --force to overwrite.", file=sys.stderr)
        return 2

    files = [f for f in sorted(CANONICAL.rglob("*"))
             if f.is_file() and not any(p in SKIP for p in f.relative_to(CANONICAL).parts)]
    actions = []
    for f in files:
        rel = f.relative_to(CANONICAL)
        actions.append(("SKILL.md(frontmatter-stripped)" if rel.as_posix() == "SKILL.md" else "copy", rel))

    if a.dry_run:
        print(f"DRY-RUN — canonical: {CANONICAL}\n         dest:      {dest}")
        for kind, rel in actions:
            print(f"  {kind:32} {rel}")
        print(f"  write                            agents/openai.yaml")
        print(f"  write                            {MARKER}")
        return 0

    if dest.exists():
        shutil.rmtree(dest)
    dest.mkdir(parents=True)
    for f in files:
        rel = f.relative_to(CANONICAL)
        target = dest / rel
        target.parent.mkdir(parents=True, exist_ok=True)
        if rel.as_posix() == "SKILL.md":
            target.write_text(strip_frontmatter_keys(f.read_text(encoding="utf-8")), encoding="utf-8")
        else:
            shutil.copy2(f, target)
    (dest / "agents").mkdir(exist_ok=True)
    (dest / "agents/openai.yaml").write_text(OPENAI_YAML, encoding="utf-8")
    (dest / MARKER).write_text(
        f"# Generated adapter — DO NOT EDIT\n\nGenerated from canonical `{CANONICAL}` by "
        "`scripts/build_adapters.py`. Edit the canonical source and regenerate.\n", encoding="utf-8")
    print(f"generated Codex adapter at {dest} ({len(files)} files + openai.yaml)")
    # sanity: the emitted SKILL.md must be Codex-clean
    sk = (dest / "SKILL.md").read_text(encoding="utf-8")
    bad = [k for k in ("argument-hint:", "allowed-tools:") if k in sk.split("---", 2)[1]] if "---" in sk else []
    if bad:
        print(f"WARN: stripped keys still present: {bad}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
